const root=document.documentElement;
const themeToggle=document.getElementById('themeToggle');
const menuBtn=document.getElementById('menuBtn');
const navLinks=document.getElementById('navLinks');
const navAnchors=[...document.querySelectorAll('.nav-links a')];
const sections=[...document.querySelectorAll('main section[id]')];
const revealItems=[...document.querySelectorAll('.reveal')];
const tiltCard=document.querySelector('.tilt-card');
const languageButtons=[...document.querySelectorAll('.language-btn')];
const customCursor=document.getElementById('customCursor');

const translations={
  en:{
    'nav.about':'About','nav.experience':'Experience','nav.projects':'Projects','nav.contact':'Contact',
    'hero.location':'Surabaya, Indonesia','hero.title':'Building useful products<br />','hero.gradient':'from backend to interface.','hero.description':"I'm <strong>Djatu Hamidan Ardiwinanto</strong>, a Full Stack Web Developer focused on dependable backend systems, clean APIs, and maintainable web applications.",'hero.explore':'Explore my work','hero.talk':"Let's talk",'hero.currentRole':'Current role','hero.currentCompany':'Current company',
    'profile.label':'PROFILE / 2026','profile.role':'FULL STACK DEVELOPER','profile.backend':'Backend-focused','profile.systems':'Web systems',
    'about.kicker':'About','about.title':'Systems that stay readable<br />after they grow.','about.p1':'My work spans web application development, transactional workflows, internal business tools, database-heavy systems, and API integrations. At Printsoft, I work on software used in printing-business operations including POS, order management, bookkeeping, and reporting.','about.p2':'I also built a reusable internal CodeIgniter 3 query-builder library to help the team write database queries that are cleaner, safer, and easier to maintain.','about.gpa':'Bachelor GPA / 4.00','about.projects':'Projects in portfolio','about.coreStack':'Core stack',
    'experience.kicker':'Experience','experience.title':'From database design<br />to production systems.','experience.presentDate':'Nov 2024 — Present','experience.current':'CURRENT','experience.printsoft1':'Develop and maintain web systems for printing-business operations, including POS, order management, bookkeeping, and reporting.','experience.printsoft2':'Build full-stack applications with CodeIgniter and MySQL.','experience.printsoft3':'Designed a reusable internal CI3 query-builder library for cleaner and more maintainable database access.','experience.printsoft4':'Design and implement REST APIs for transactional and operational workflows.','experience.gocement1':'Developed, maintained, troubleshot, and improved backend systems handling customer data.','experience.gocement2':'Implemented backend features with focus on speed, robustness, and security.','experience.gocement3':'Integrated Algolia product search and Twilio for 2FA and marketing needs.','experience.internRole':'Software Developer Intern','experience.bmi1':'Designed database structures using CDM/PDM.','experience.bmi2':'Built an investment monitoring & evaluation system with Python/Django.','experience.bmi3':'Built a seafood warehouse inventory system with Python/Django.','experience.labRole':'Database Design Lab Assistant','experience.lab1':'Assisted lecturers in teaching and guiding students on database-related topics.','experience.lab2':'Helped students solve database questions and acted as liaison between students and lecturers.',
    'projects.kicker':'Selected projects','projects.title':"Things I've designed<br />and shipped.",'projects.cqb':'A drop-in, backward-compatible extension of CodeIgniter 3 Query Builder with Laravel-inspired eager loading, aggregate subqueries, WHERE EXISTS / WHERE HAS, chunking, and more.','projects.cqbMeta':'99 documented public methods · 118-test MySQL & SQLite suites','projects.github':'View on GitHub','projects.pos':'A point-of-sale system for sales and inventory management, built to monitor stock and track inventory history efficiently.','projects.libraryTitle':'Campus Library Visitor Dashboard','projects.library':'Flexible dashboard showing visitor percentages across study programs, lecturers, staff, and external guests.','projects.chat':'Room-based real-time messaging application implemented with WebSocket and MySQL.','projects.investmentTitle':'Investment Monitoring & Evaluation','projects.investment':'Tracks target versus realization using the Hanumm Curve / S-Curve method, with investment data refreshed every five seconds.','projects.employeeTitle':'Employee Recruitment DSS','projects.employee':'A decision-support system that ranks recruitment recommendations based on selected HR criteria.','projects.guesthouseTitle':'Guesthouse Booking System','projects.guesthouse':'Room availability, booking, and post-stay review workflow built with Laravel and MySQL.','projects.laptopTitle':'Laptop Purchase DSS','projects.laptop':'Recommendation system combining AHP and SAW methods to rank laptops from user-selected criteria.',
    'education.kicker':'Education','education.title':'Foundation in<br />Information Systems.','education.degree':'Bachelor Degree in Sistem Informasi',
    'contact.kicker':'Contact','contact.title':'Have a project or<br />an opportunity in mind?','contact.copy':'Reach me directly by email, WhatsApp, or LinkedIn.','footer.built':'Designed & built with HTML, CSS & JavaScript.'
  },
  id:{
    'nav.about':'Tentang','nav.experience':'Pengalaman','nav.projects':'Proyek','nav.contact':'Kontak',
    'hero.location':'Surabaya, Indonesia','hero.title':'Membangun produk yang berguna<br />','hero.gradient':'dari backend hingga antarmuka.','hero.description':'Saya <strong>Djatu Hamidan Ardiwinanto</strong>, seorang Full Stack Web Developer yang berfokus pada sistem backend yang andal, API yang rapi, dan aplikasi web yang mudah dipelihara.','hero.explore':'Lihat karya saya','hero.talk':'Mari bicara','hero.currentRole':'Posisi saat ini','hero.currentCompany':'Perusahaan saat ini',
    'profile.label':'PROFIL / 2026','profile.role':'FULL STACK DEVELOPER','profile.backend':'Fokus backend','profile.systems':'Sistem web',
    'about.kicker':'Tentang','about.title':'Sistem yang tetap mudah dibaca<br />meski terus berkembang.','about.p1':'Pekerjaan saya mencakup pengembangan aplikasi web, alur transaksi, tools internal bisnis, sistem yang berat di database, dan integrasi API. Di Printsoft, saya mengembangkan software untuk operasional bisnis percetakan seperti POS, manajemen pesanan, pembukuan, dan pelaporan.','about.p2':'Saya juga membangun library query builder internal CodeIgniter 3 yang reusable agar tim dapat menulis query database yang lebih bersih, aman, dan mudah dipelihara.','about.gpa':'IPK Sarjana / 4.00','about.projects':'Proyek dalam portfolio','about.coreStack':'Stack utama',
    'experience.kicker':'Pengalaman','experience.title':'Dari desain database<br />hingga sistem produksi.','experience.presentDate':'Nov 2024 — Sekarang','experience.current':'SEKARANG','experience.printsoft1':'Mengembangkan dan memelihara sistem web untuk operasional bisnis percetakan, termasuk POS, manajemen pesanan, pembukuan, dan pelaporan.','experience.printsoft2':'Membangun aplikasi full-stack dengan CodeIgniter dan MySQL.','experience.printsoft3':'Merancang library query builder internal CI3 yang reusable untuk akses database yang lebih bersih dan mudah dipelihara.','experience.printsoft4':'Merancang dan mengimplementasikan REST API untuk alur kerja transaksional dan operasional.','experience.gocement1':'Mengembangkan, memelihara, melakukan troubleshooting, dan meningkatkan sistem backend yang menangani data pelanggan.','experience.gocement2':'Mengimplementasikan fitur backend dengan fokus pada kecepatan, ketahanan, dan keamanan.','experience.gocement3':'Mengintegrasikan pencarian produk Algolia dan Twilio untuk 2FA serta kebutuhan pemasaran.','experience.internRole':'Software Developer (Magang)','experience.bmi1':'Merancang struktur database menggunakan CDM/PDM.','experience.bmi2':'Membangun sistem monitoring & evaluasi investasi dengan Python/Django.','experience.bmi3':'Membangun sistem inventori gudang hasil laut dengan Python/Django.','experience.labRole':'Asisten Laboratorium Desain Database','experience.lab1':'Membantu dosen mengajar dan membimbing mahasiswa terkait topik database.','experience.lab2':'Membantu mahasiswa menyelesaikan pertanyaan database dan menjadi penghubung antara mahasiswa dan dosen.',
    'projects.kicker':'Proyek pilihan','projects.title':'Hal yang saya rancang<br />dan bangun.','projects.cqb':'Ekstensi drop-in dan backward-compatible untuk CodeIgniter 3 Query Builder dengan fitur bergaya Laravel seperti eager loading, aggregate subqueries, WHERE EXISTS / WHERE HAS, chunking, dan lainnya.','projects.cqbMeta':'99 public method terdokumentasi · 118 test untuk MySQL & SQLite','projects.github':'Lihat di GitHub','projects.pos':'Sistem point-of-sale untuk pengelolaan penjualan dan inventori, dirancang untuk memantau stok dan riwayat inventori secara efisien.','projects.libraryTitle':'Dashboard Pengunjung Perpustakaan Kampus','projects.library':'Dashboard fleksibel yang menampilkan persentase pengunjung dari program studi, dosen, karyawan, dan tamu eksternal.','projects.chat':'Aplikasi pesan realtime berbasis room yang dibangun menggunakan WebSocket dan MySQL.','projects.investmentTitle':'Monitoring & Evaluasi Investasi','projects.investment':'Membandingkan target dan realisasi menggunakan metode Kurva Hanumm / Kurva-S, dengan data investasi diperbarui setiap lima detik.','projects.employeeTitle':'SPK Penerimaan Karyawan','projects.employee':'Sistem pendukung keputusan yang memberi peringkat rekomendasi perekrutan berdasarkan kriteria SDM.','projects.guesthouseTitle':'Sistem Pemesanan Guesthouse','projects.guesthouse':'Alur ketersediaan kamar, pemesanan, dan ulasan setelah menginap menggunakan Laravel dan MySQL.','projects.laptopTitle':'SPK Pembelian Laptop','projects.laptop':'Sistem rekomendasi yang menggabungkan metode AHP dan SAW untuk memberi peringkat laptop berdasarkan kriteria pengguna.',
    'education.kicker':'Pendidikan','education.title':'Fondasi di bidang<br />Sistem Informasi.','education.degree':'Sarjana Sistem Informasi',
    'contact.kicker':'Kontak','contact.title':'Punya proyek atau<br />peluang untuk dibicarakan?','contact.copy':'Hubungi saya langsung melalui email, WhatsApp, atau LinkedIn.','footer.built':'Dirancang & dibangun dengan HTML, CSS & JavaScript.'
  }
};

const savedTheme=localStorage.getItem('portfolio-theme');
const preferredTheme=matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';
root.dataset.theme=savedTheme||preferredTheme;
themeToggle?.addEventListener('click',()=>{const next=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=next;localStorage.setItem('portfolio-theme',next)});

menuBtn?.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});
navAnchors.forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuBtn?.setAttribute('aria-expanded','false')}));

let currentLanguage='en',languageTransitionId=0;
function applyLanguage(lang){const d=translations[lang]||translations.en;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(d[k]!=null)el.textContent=d[k]});document.querySelectorAll('[data-i18n-html]').forEach(el=>{const k=el.dataset.i18nHtml;if(d[k]!=null)el.innerHTML=d[k]});root.lang=lang;localStorage.setItem('portfolio-language',lang);languageButtons.forEach(b=>{const active=b.dataset.lang===lang;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});currentLanguage=lang}
function setLanguage(lang,animate=true){if(!translations[lang])lang='en';if(lang===currentLanguage)return;const id=++languageTransitionId;if(!animate||matchMedia('(prefers-reduced-motion: reduce)').matches){root.classList.remove('language-leaving','language-entering');applyLanguage(lang);return}root.classList.remove('language-entering');root.classList.add('language-leaving');setTimeout(()=>{if(id!==languageTransitionId)return;applyLanguage(lang);root.classList.remove('language-leaving');root.classList.add('language-entering');setTimeout(()=>{if(id===languageTransitionId)root.classList.remove('language-entering')},300)},160)}
languageButtons.forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang,true)));
const savedLanguage=localStorage.getItem('portfolio-language');
const browserLanguage=navigator.language?.toLowerCase().startsWith('id')?'id':'en';
applyLanguage(savedLanguage&&translations[savedLanguage]?savedLanguage:browserLanguage);

revealItems.forEach(i=>i.style.setProperty('--delay',`${Number(i.dataset.delay||0)}ms`));
const revealObserver=new IntersectionObserver((entries,obs)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -30px'});
revealItems.forEach(i=>revealObserver.observe(i));
const sectionObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;navAnchors.forEach(link=>link.classList.toggle('active',link.getAttribute('href').slice(1)===e.target.id))}),{threshold:.35,rootMargin:'-20% 0px -45%'});
sections.forEach(s=>sectionObserver.observe(s));

if(tiltCard&&matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){tiltCard.addEventListener('pointermove',e=>{const r=tiltCard.getBoundingClientRect(),px=(e.clientX-r.left)/r.width,py=(e.clientY-r.top)/r.height;tiltCard.style.transform=`rotateX(${(0.5-py)*7}deg) rotateY(${(px-.5)*7}deg) translateY(-2px)`});tiltCard.addEventListener('pointerleave',()=>tiltCard.style.transform='rotateX(0deg) rotateY(0deg) translateY(0)')}

if(customCursor&&matchMedia('(pointer:fine)').matches&&matchMedia('(hover:hover)').matches){root.classList.add('custom-cursor-enabled');const move=e=>{customCursor.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0) translate(-50%,-50%)`;customCursor.classList.add('is-visible')};window.addEventListener('pointermove',move,{passive:true});document.addEventListener('pointerover',e=>customCursor.classList.toggle('is-hovering',!!e.target.closest('a,button,[role="button"]')));document.addEventListener('pointerdown',()=>customCursor.classList.add('is-pressed'));document.addEventListener('pointerup',()=>customCursor.classList.remove('is-pressed'));document.addEventListener('mouseleave',()=>customCursor.classList.remove('is-visible'))}

document.getElementById('year').textContent=new Date().getFullYear();
